
export const TIPOS_ERROR = {
    TIPO_DE_DATOS: 400,
    ARGUMENTOS_INVALIDOS: 400,
    PRODUCTO_EXISTENTE:400,
    AUTENTICATION:401,
    AUTORIZACION: 403,
    NOT_FOUND: 404,
    INTENRAL_SERVER_ERROR: 500
}